// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=mocks/contract.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	models "github.com/mams/backend/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockReader is a mock of Reader interface.
type MockReader struct {
	ctrl     *gomock.Controller
	recorder *MockReaderMockRecorder
	isgomock struct{}
}

// MockReaderMockRecorder is the mock recorder for MockReader.
type MockReaderMockRecorder struct {
	mock *MockReader
}

// NewMockReader creates a new mock instance.
func NewMockReader(ctrl *gomock.Controller) *MockReader {
	mock := &MockReader{ctrl: ctrl}
	mock.recorder = &MockReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReader) EXPECT() *MockReaderMockRecorder {
	return m.recorder
}

// Append mocks base method.
func (m *MockReader) Append(ctx context.Context, serviceID uuid.UUID, env, level, message string) *models.LogEntry {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Append", ctx, serviceID, env, level, message)
	ret0, _ := ret[0].(*models.LogEntry)
	return ret0
}

// Append indicates an expected call of Append.
func (mr *MockReaderMockRecorder) Append(ctx, serviceID, env, level, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Append", reflect.TypeOf((*MockReader)(nil).Append), ctx, serviceID, env, level, message)
}

// ListByService mocks base method.
func (m *MockReader) ListByService(ctx context.Context, serviceID uuid.UUID, filter models.LogFilter) ([]models.LogEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByService", ctx, serviceID, filter)
	ret0, _ := ret[0].([]models.LogEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByService indicates an expected call of ListByService.
func (mr *MockReaderMockRecorder) ListByService(ctx, serviceID, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByService", reflect.TypeOf((*MockReader)(nil).ListByService), ctx, serviceID, filter)
}
