// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=mocks/contract.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	models "github.com/mams/backend/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockServiceReader is a mock of ServiceReader interface.
type MockServiceReader struct {
	ctrl     *gomock.Controller
	recorder *MockServiceReaderMockRecorder
	isgomock struct{}
}

// MockServiceReaderMockRecorder is the mock recorder for MockServiceReader.
type MockServiceReaderMockRecorder struct {
	mock *MockServiceReader
}

// NewMockServiceReader creates a new mock instance.
func NewMockServiceReader(ctrl *gomock.Controller) *MockServiceReader {
	mock := &MockServiceReader{ctrl: ctrl}
	mock.recorder = &MockServiceReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceReader) EXPECT() *MockServiceReaderMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockServiceReader) GetByID(ctx context.Context, id uuid.UUID) (models.Service, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(models.Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockServiceReaderMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockServiceReader)(nil).GetByID), ctx, id)
}
