// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=mocks/contract.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	models "github.com/mams/backend/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockServiceReader is a mock of ServiceReader interface.
type MockServiceReader struct {
	ctrl     *gomock.Controller
	recorder *MockServiceReaderMockRecorder
	isgomock struct{}
}

// MockServiceReaderMockRecorder is the mock recorder for MockServiceReader.
type MockServiceReaderMockRecorder struct {
	mock *MockServiceReader
}

// NewMockServiceReader creates a new mock instance.
func NewMockServiceReader(ctrl *gomock.Controller) *MockServiceReader {
	mock := &MockServiceReader{ctrl: ctrl}
	mock.recorder = &MockServiceReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceReader) EXPECT() *MockServiceReaderMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockServiceReader) GetByID(ctx context.Context, id uuid.UUID) (models.Service, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(models.Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockServiceReaderMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockServiceReader)(nil).GetByID), ctx, id)
}

// MockOrganizationReader is a mock of OrganizationReader interface.
type MockOrganizationReader struct {
	ctrl     *gomock.Controller
	recorder *MockOrganizationReaderMockRecorder
	isgomock struct{}
}

// MockOrganizationReaderMockRecorder is the mock recorder for MockOrganizationReader.
type MockOrganizationReaderMockRecorder struct {
	mock *MockOrganizationReader
}

// NewMockOrganizationReader creates a new mock instance.
func NewMockOrganizationReader(ctrl *gomock.Controller) *MockOrganizationReader {
	mock := &MockOrganizationReader{ctrl: ctrl}
	mock.recorder = &MockOrganizationReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrganizationReader) EXPECT() *MockOrganizationReaderMockRecorder {
	return m.recorder
}

// GetSlugByID mocks base method.
func (m *MockOrganizationReader) GetSlugByID(ctx context.Context, id uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSlugByID", ctx, id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSlugByID indicates an expected call of GetSlugByID.
func (mr *MockOrganizationReaderMockRecorder) GetSlugByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSlugByID", reflect.TypeOf((*MockOrganizationReader)(nil).GetSlugByID), ctx, id)
}

// MockReleaseReader is a mock of ReleaseReader interface.
type MockReleaseReader struct {
	ctrl     *gomock.Controller
	recorder *MockReleaseReaderMockRecorder
	isgomock struct{}
}

// MockReleaseReaderMockRecorder is the mock recorder for MockReleaseReader.
type MockReleaseReaderMockRecorder struct {
	mock *MockReleaseReader
}

// NewMockReleaseReader creates a new mock instance.
func NewMockReleaseReader(ctrl *gomock.Controller) *MockReleaseReader {
	mock := &MockReleaseReader{ctrl: ctrl}
	mock.recorder = &MockReleaseReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReleaseReader) EXPECT() *MockReleaseReaderMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockReleaseReader) Create(ctx context.Context, rel models.Release) (models.Release, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, rel)
	ret0, _ := ret[0].(models.Release)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockReleaseReaderMockRecorder) Create(ctx, rel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockReleaseReader)(nil).Create), ctx, rel)
}

// GetByID mocks base method.
func (m *MockReleaseReader) GetByID(ctx context.Context, id uuid.UUID) (models.Release, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(models.Release)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockReleaseReaderMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockReleaseReader)(nil).GetByID), ctx, id)
}

// ListByService mocks base method.
func (m *MockReleaseReader) ListByService(ctx context.Context, serviceID uuid.UUID) ([]models.Release, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByService", ctx, serviceID)
	ret0, _ := ret[0].([]models.Release)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByService indicates an expected call of ListByService.
func (mr *MockReleaseReaderMockRecorder) ListByService(ctx, serviceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByService", reflect.TypeOf((*MockReleaseReader)(nil).ListByService), ctx, serviceID)
}

// UpdateServiceVersion mocks base method.
func (m *MockReleaseReader) UpdateServiceVersion(ctx context.Context, serviceID uuid.UUID, version string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateServiceVersion", ctx, serviceID, version)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateServiceVersion indicates an expected call of UpdateServiceVersion.
func (mr *MockReleaseReaderMockRecorder) UpdateServiceVersion(ctx, serviceID, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateServiceVersion", reflect.TypeOf((*MockReleaseReader)(nil).UpdateServiceVersion), ctx, serviceID, version)
}

// UpdateStatus mocks base method.
func (m *MockReleaseReader) UpdateStatus(ctx context.Context, id uuid.UUID, status string) (models.Release, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(models.Release)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockReleaseReaderMockRecorder) UpdateStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockReleaseReader)(nil).UpdateStatus), ctx, id, status)
}

// MockWorkflowDispatcher is a mock of WorkflowDispatcher interface.
type MockWorkflowDispatcher struct {
	ctrl     *gomock.Controller
	recorder *MockWorkflowDispatcherMockRecorder
	isgomock struct{}
}

// MockWorkflowDispatcherMockRecorder is the mock recorder for MockWorkflowDispatcher.
type MockWorkflowDispatcherMockRecorder struct {
	mock *MockWorkflowDispatcher
}

// NewMockWorkflowDispatcher creates a new mock instance.
func NewMockWorkflowDispatcher(ctrl *gomock.Controller) *MockWorkflowDispatcher {
	mock := &MockWorkflowDispatcher{ctrl: ctrl}
	mock.recorder = &MockWorkflowDispatcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkflowDispatcher) EXPECT() *MockWorkflowDispatcherMockRecorder {
	return m.recorder
}

// DispatchWorkflow mocks base method.
func (m *MockWorkflowDispatcher) DispatchWorkflow(ctx context.Context, repositoryURL, workflowID, ref string, inputs map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DispatchWorkflow", ctx, repositoryURL, workflowID, ref, inputs)
	ret0, _ := ret[0].(error)
	return ret0
}

// DispatchWorkflow indicates an expected call of DispatchWorkflow.
func (mr *MockWorkflowDispatcherMockRecorder) DispatchWorkflow(ctx, repositoryURL, workflowID, ref, inputs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DispatchWorkflow", reflect.TypeOf((*MockWorkflowDispatcher)(nil).DispatchWorkflow), ctx, repositoryURL, workflowID, ref, inputs)
}

// MockKubeDeployer is a mock of KubeDeployer interface.
type MockKubeDeployer struct {
	ctrl     *gomock.Controller
	recorder *MockKubeDeployerMockRecorder
	isgomock struct{}
}

// MockKubeDeployerMockRecorder is the mock recorder for MockKubeDeployer.
type MockKubeDeployerMockRecorder struct {
	mock *MockKubeDeployer
}

// NewMockKubeDeployer creates a new mock instance.
func NewMockKubeDeployer(ctrl *gomock.Controller) *MockKubeDeployer {
	mock := &MockKubeDeployer{ctrl: ctrl}
	mock.recorder = &MockKubeDeployerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKubeDeployer) EXPECT() *MockKubeDeployerMockRecorder {
	return m.recorder
}

// ApplyCanaryPatch mocks base method.
func (m *MockKubeDeployer) ApplyCanaryPatch(ctx context.Context, namespace, name, canaryName, container, image string, replicas int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyCanaryPatch", ctx, namespace, name, canaryName, container, image, replicas)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyCanaryPatch indicates an expected call of ApplyCanaryPatch.
func (mr *MockKubeDeployerMockRecorder) ApplyCanaryPatch(ctx, namespace, name, canaryName, container, image, replicas any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyCanaryPatch", reflect.TypeOf((*MockKubeDeployer)(nil).ApplyCanaryPatch), ctx, namespace, name, canaryName, container, image, replicas)
}

// RollbackToTag mocks base method.
func (m *MockKubeDeployer) RollbackToTag(ctx context.Context, namespace, name, container, image string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RollbackToTag", ctx, namespace, name, container, image)
	ret0, _ := ret[0].(error)
	return ret0
}

// RollbackToTag indicates an expected call of RollbackToTag.
func (mr *MockKubeDeployerMockRecorder) RollbackToTag(ctx, namespace, name, container, image any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RollbackToTag", reflect.TypeOf((*MockKubeDeployer)(nil).RollbackToTag), ctx, namespace, name, container, image)
}

// UpgradeRecreate mocks base method.
func (m *MockKubeDeployer) UpgradeRecreate(ctx context.Context, namespace, name, container, image string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpgradeRecreate", ctx, namespace, name, container, image)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpgradeRecreate indicates an expected call of UpgradeRecreate.
func (mr *MockKubeDeployerMockRecorder) UpgradeRecreate(ctx, namespace, name, container, image any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpgradeRecreate", reflect.TypeOf((*MockKubeDeployer)(nil).UpgradeRecreate), ctx, namespace, name, container, image)
}

// UpgradeRolling mocks base method.
func (m *MockKubeDeployer) UpgradeRolling(ctx context.Context, namespace, name, container, image string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpgradeRolling", ctx, namespace, name, container, image)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpgradeRolling indicates an expected call of UpgradeRolling.
func (mr *MockKubeDeployerMockRecorder) UpgradeRolling(ctx, namespace, name, container, image any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpgradeRolling", reflect.TypeOf((*MockKubeDeployer)(nil).UpgradeRolling), ctx, namespace, name, container, image)
}
